---
title: 주제별 카테고리
author: ''
date: '2018-04-26'
slug: topic_categories
categories: []
tags: []
---

각 주제별 카테고리와 관련된 Post는 우측 카테고리 메뉴에서 최신 순으로 확인할 수 있습니다.

---

#### 농업 통계

농업생산, 농가경제통계, 농산물 생산비조사, 농산물 소득조사와 같은 [통계청][kostat], [농촌진흥청][https://amis.rda.go.kr] 등에서 제공하는 통계자료 분석 관련 Post를 게재한다.   

---

#### 생산과 유통

농축산물 생산과정에서의 생산정보관리시스템(Production Infromation Management System, PIMS) 도입은 생산성 향상 뿐만 아니라 경영성과 평가를 통해 경영체가 지속적인 성장이 가능하도록 돕는다. 국내에서는 단일 품목의 산업 규모가 큰 축산분야에서 PIMS가 많이 사용되고 있는데, 특히 양돈 분야에서는 2000년부터 보급된 [PigPlan](http://www.pigplan.com)에 국내 모돈의 30% 가량의 방대한 정보가 축적되어 있다. 

유통 분야에서는 도매시장에서 경매되는 모든 농축산물의 가격, 거래량 등의 방대한 정보가 유관 공공기관의 전산망을 통해 축적되고 있다. 농산물 유통정보는 한국농수산식품유통공사에서 운영하는 [KAMIS][kamis] 에서 제공되고 있고, 축산물 유통정보는 축산물품질평가원에서 운영하는 [축산물유통종합정보센터](http://www.ekapepia.com/)에서 제공되고 있다. 

생산과 유통 카테고리에서는 생산정보와 도매시장 유통정보 데이터 분석과 관련한 Post를 게재한다. 

---

#### 환경모니터링과 제어

작물의 생장에 영향을 미치는 외부 환경요소에 대한 실시간 측정데이터는 농업 분야의 빅데이터 중 가장 일찍부터 쌓여 오고 있다. 모니터링하는 외부 환경 요소가 작물의 생장 조건에 최적이 되는 범위에서 유지되는 것이 가장 중요한 관리 포인트이다. 온실의 경우라도 낮과 밤이 교차함에 따라 작물의 외부 환경 변화가 크기 때문에 여러 환경 조절 장치들을 적절하게 제어해서 최적의 범위를 유지하는 것이 필요하며, 이와 관련된 Post를 게재한다.  

---

#### 과학과 기술

과학과 기술 카테고리에는 과학기술 관련 토픽별 주제에 대한 Post, 통계와 머신러닝 등의 방법론에 관한 Post, R과 Python 과 같은 분석도구에 대한 Post를 게재한다. 

###### Topic - 빅데이터, IoT, 인공지능, 4차산업혁명 

* 빅데이터 : 농업분야 빅데이터에 대한 더 많은 정보는 [농림축산식품공공데이터포털](https://data.mafra.go.kr/) 에서 탐색할 수 있다.

###### Method - 통계, 계량경제, 머신러닝

* 농업정보시스템 연구실 시계열 방법론 수업 R 실습 자료 : Post
* 농업정보시스템 연구실 빅데이터 방법론 수업 R 실습 자료 : Post 

###### Tool - R, Python

 * R - 통계기반 모델링을 위한 최고의 친구 
 * R shiny - R 분석 결과를 웹에서 대시보드 형태로 보고싶을 때
 * R blogdown - R 분석 결과를 웹에서 블로그 형태로 보고싶을 때 
 * Python - R보다 머신러닝과 웹 연계 기능에서 앞서가는 친구
 * Keras - Tensorflow를 이용한 딥러닝을 쉽게 할 수 있게 해주는 친구

---

[kostat]: <https://kostat.go.kr/>
[kamis]: <https://www.kamis.or.kr>
