---
title: 원산지정보와 국제광고(랩스터디)
author: '김성제 '
date: '2018-05-04'
slug: orgin_intnl_ad
categories:
  - 랩스터디
tags:
  - MANOVA
description: ''
thumbnail: ''
---

<iframe src="//www.slideshare.net/slideshow/embed_code/key/agPK83uXL6sYR2" width="595" height="485" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/SungjayKim1/ss-95910976" title="원산지정보의 강조와 소비자의 자민족중심주의 성향이 국제광고 효과에 미치는 영향" target="_blank">원산지정보의 강조와 소비자의 자민족중심주의 성향이 국제광고 효과에 미치는 영향</a> </strong> from <strong><a href="https://www.slideshare.net/SungjayKim1" target="_blank">Sungjay Kim</a></strong> </div>

---


#### 코멘트

###### 진용's comment

* 본 논문은 원산지 정보의 강조와 자민족중심주의가 국제광고에 대한 소비자 반응에 미치는 영향을 원산지 이미지, 제품유형, 제품 관여도의 조절효과를 중심으로 살펴봄으로써 국제광고에서 원산지 효과가 발생하는 구조를 분석하고 있다. 논문을 읽으며 흥미로웠던 점은 세미나에서 기존에 많이 읽었던 논문들과 달리, 기존의 데이터를 이용하지 않고 새로 실험을 설계하여 데이터를 얻었다는 점이다. 그 실험 과정과 그로부터 나온 데이터를 분석하는 과정이 굉장히 체계적이라는 것이 인상깊었다. 또한 연구에서 세운 모든 가설들을 원산지 이미지 및 제품 유형에 따라 그룹화 시켜 분석함으로써 보다 다양한 결론을 도출했다는 것이 흥미로우며, 이후 내가 농업이나 식품과 관련하여 진행할 연구에서도 충분히 활용할 수 있는 부분이라 유익했다. 

###### 연진's comment

* 글로벌 시장에서 원산지는 외국산 제품을 평가하는 중요한 단서이다. 이에 따라 다국적기업들은 해당기업이 속하는 국가의 이미지를 고려한 마케팅 전략을 수립할 필요가 있다. 이러한 중요성에도 불구하고 원산지 이미지에 관한 기존의 연구들은 이론적 틀의 불확실성, 다양한 조절변인 고려 부족, 서로 다른 조절변인 정의 및 사용 등이 한계를 가지고 있다. 이에 해당 연구에서는 기존 연구들의 한계를 보완하여 원산지 정보의 강조가 국제광고에 대한 소비자 반응에 미치는 영향을 밝히고 있으며 해당 주제에서 주된 요인으로 여겨지는 자민족중심주의의 영향 역시 분석하였다. 

* 해당 연구에서는 원산지 단서의 강조, 원산지 이미지, 제품유형, 자민족중심주의가 변인으로 사용되었고 종속변인인 광고에 대한 소비자 반응은 광고에 대한 신뢰도, 브랜드에 대한 신뢰도, 광고된 제품의 품질인식이 사용되었다. 이 논문에서는 다변량 분산분석이 사용되었는데 이는 종속변수가 여러 개일 경우 사용되는 방법으로 종속변수간의 상관을 분석에 반영할 수 있으며, 개별 ANOVA를 시행할 경우 1종 오류를 범할 확률이 높아지는데 이를 방지할 수 있다는 특징이 있다.

* 이 논문에서는 독립변인을 연구자의 임의로 조작 설정하였다. 설정한 변인이 연구자의 의도대로 지각됐는지 검증하기 위해 일원변량분석을 실시하여 조작점검을 실시하였지만 설정한 이론적 근거가 없는 점은 아쉽다. 또한 변인을 설정하기 위해 사전에 20명을 대상으로 조사를 실시하였는데 20명의 샘플은 대표성을 갖기에 너무 작다.

